name: Python Checks

on: [pull_request]

jobs:
  type_and_docstring_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mypy pydocstyle requests

    - name: Run mypy and save output
      run: mypy --ignore-missing-imports . > mypy_output.txt 2>&1
      continue-on-error: true

    - name: Run pydocstyle and save output
      run: pydocstyle . > pydocstyle_output.txt 2>&1
      continue-on-error: true

    - name: Set script permissions
      run: chmod +x .github/scripts/comment_pr.py

    - name: Comment PR
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: python .github/scripts/comment_pr.py
