name: Python Checks

on: [pull_request]

permissions:
  issues: write
  pull-requests: write

jobs:
  type_and_docstring_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Fetch base branch
      run: git fetch --depth=1 origin ${{ github.base_ref }}:${{ github.base_ref }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mypy pydocstyle requests

    - name: Find modified Python files
      id: modified_files
      run: |
        echo "MODIFIED_FILES<<EOF" >> $GITHUB_ENV
        git diff --name-only FETCH_HEAD $(git merge-base FETCH_HEAD ${{ github.head_ref }}) | grep '\.py$'
        echo "EOF" >> $GITHUB_ENV

    - name: Run mypy and save output
      if: env.MODIFIED_FILES != ''
      run: |
        mypy --ignore-missing-imports --disallow-untyped-defs ${{ env.MODIFIED_FILES }} > mypy_output.txt 2>&1
      continue-on-error: true

    - name: Run pydocstyle and save output
      if: env.MODIFIED_FILES != ''
      run: pydocstyle ${{ env.MODIFIED_FILES }} > pydocstyle_output.txt 2>&1
      continue-on-error: true

    - name: Set script permissions
      run: chmod +x .github/scripts/comment_pr.py

    - name: Comment PR
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: python .github/scripts/comment_pr.py
