name: flake8 Lint

on: [pull_request]

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      # Install specific flake8 version (this step is not required. Default is "latest").
      - run: pip install flake8
      # Install flake8 extensions (this step is not required. Default is "None").
      - run: pip install flake8-docstrings flake8-simplify flake8-unused-arguments flake8-quotes flake8-annotations
      - name: flake8 Lint
        uses: reviewdog/action-flake8@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}